version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: 161103
      POSTGRES_USER: postgres
      POSTGRES_DB: juniorcase_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - juniorcase-network
  jsp-app:
    image: al3zin/jsp-app
    restart: always
    build: ./Java-Spring-Boot-RESTful-Api
    working_dir: /Java-Spring-Boot-RESTful-Api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-db:5432/juniorcase_db?useTimeZone=true&serverTimeZone=UTC
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 161103
    ports:
      - 8080:8888
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - juniorcase-network
networks:
  juniorcase-network:
    driver: bridge