version: '3.9'
services:
  mysql-db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 161103
      MYSQL_USER: docker
      MYSQL_PASSWORD: 161103
      MYSQL_DATABASE: juniorcase_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - juniorcase-network
  jsp-app:
    image: al3zin/jps-app
    restart: always
    build: ./Java-Spring-Boot-RESTful-Api
    working_dir: /Java-Spring-Boot-RESTful-Api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-db:3308/juniorcase_db?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 161103
    ports:
      - 80:8888
    command: mvn spring-boot:run
    depends_on:
      - mysql-db
    networks:
      - juniorcase-network
networks:
  juniorcase-network:
    driver: bridge