server:
  port: 8888

cors:
  originPatterns:
    - "http://localhost:8080"
    - "http://localhost:4200"

spring:
  profiles: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/juniorcase_db?useTimeZone=true&serverTimeZone=UTC
    username: postgres
    password: 161103

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  pathsToMatch:
    - "/auth/**"
    - "/api/**/v1/**"
  swagger-ui:
    use-root-path: true
